ALTER TYPE "ImportType" ADD VALUE IF NOT EXISTS 'CLASS';
ALTER TYPE "ImportType" ADD VALUE IF NOT EXISTS 'SECTION';
ALTER TYPE "ImportType" ADD VALUE IF NOT EXISTS 'SUBJECT';
ALTER TYPE "ImportType" ADD VALUE IF NOT EXISTS 'EXPENSE_CATEGORY';
ALTER TYPE "ImportType" ADD VALUE IF NOT EXISTS 'EXPENSE';
