ALTER TABLE "subscriptions"
ADD COLUMN IF NOT EXISTS "billing_cycle" TEXT NOT NULL DEFAULT 'MONTHLY',
ADD COLUMN IF NOT EXISTS "discount_percent" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "grace_days" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN IF NOT EXISTS "paid_at" TIMESTAMP,
ADD COLUMN IF NOT EXISTS "next_due_at" TIMESTAMP;
