export {
  createFeeParticular,
  createFeeStructure,
  createFeeType,
  deleteFeeParticular,
  deleteFeeStructure,
  deleteFeeType,
  duplicateFeeStructure,
  getFeeMetadata,
  listFeeParticulars,
  listFeeStructures,
  listFeeTypes,
  updateFeeParticular,
  updateFeeStructure,
  updateFeeType,
} from '../fee-management.core';

import {
  createFeeParticular,
  createFeeStructure,
  createFeeType,
  deleteFeeParticular,
  deleteFeeStructure,
  deleteFeeType,
  duplicateFeeStructure,
  getFeeMetadata,
  listFeeParticulars,
  listFeeStructures,
  listFeeTypes,
  updateFeeParticular,
  updateFeeStructure,
  updateFeeType,
} from '../fee-management.core';

export const FeeStructureService = {
  createFeeParticular,
  createFeeStructure,
  createFeeType,
  deleteFeeParticular,
  deleteFeeStructure,
  deleteFeeType,
  duplicateFeeStructure,
  getFeeMetadata,
  listFeeParticulars,
  listFeeStructures,
  listFeeTypes,
  updateFeeParticular,
  updateFeeStructure,
  updateFeeType,
};
